import React from "react";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>
          Gugli - the best blockchain application development company
        </title>
        <meta name="robots" content="all" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      {children}
    </>
  );
};

export default Layout;
